#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Copyright SIL International 2009 - 2025.

This file is part of SooSL™.
 
SooSL™ is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
SooSL™ is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 
You should have received a copy of the GNU General Public License
along with SooSL™.  If not, see <http://www.gnu.org/licenses/>.
"""

"""Dictionary of symbol code descriptions for the ISWA and other SooSL component symbols"""

from collections import OrderedDict
from PyQt5.QtCore import QObject
from PyQt5.QtWidgets import qApp

class ComponentDescriptions(QObject):
# removed many not used in SooSL; see component_descriptions_full_listing.py in "workshop"
    
    def symbol_dict(self):
        return OrderedDict([
        ('100', qApp.instance().translate('ComponentDescriptions', 'Index')),
        ('101', qApp.instance().translate('ComponentDescriptions', 'Index on Circle')),
        ('102', qApp.instance().translate('ComponentDescriptions', 'Index on Cup')),
        ('103', qApp.instance().translate('ComponentDescriptions', 'Index on Oval')),
        ('104', qApp.instance().translate('ComponentDescriptions', 'Index on Hinge')),
        ('105', qApp.instance().translate('ComponentDescriptions', 'Index on Angle')),
        ('106', qApp.instance().translate('ComponentDescriptions', 'Index Bent')),
        ('107', qApp.instance().translate('ComponentDescriptions', 'Index Bent on Circle')),
        ('108', qApp.instance().translate('ComponentDescriptions', 'Index Bent on Fist Thumb Under')),
        ('109', qApp.instance().translate('ComponentDescriptions', 'Index Raised Knuckle')),
        ('10a', qApp.instance().translate('ComponentDescriptions', 'Index Cup')),
        ('10b', qApp.instance().translate('ComponentDescriptions', 'Index Hinge')),
        ('10c', qApp.instance().translate('ComponentDescriptions', 'Index Hinge Low')),
        ('10d', qApp.instance().translate('ComponentDescriptions', 'Index Hinge on Circle')),
        ('10e', qApp.instance().translate('ComponentDescriptions', 'Index Middle')),
        ('10f', qApp.instance().translate('ComponentDescriptions', 'Index Middle on Circle')),
        ('110', qApp.instance().translate('ComponentDescriptions', 'Index Middle Bent')),
        ('111', qApp.instance().translate('ComponentDescriptions', 'Index Middle Raised Knuckles')),
        ('112', qApp.instance().translate('ComponentDescriptions', 'Index Middle Hinge')),
        ('113', qApp.instance().translate('ComponentDescriptions', 'Index Up, Middle Hinge')),
        ('114', qApp.instance().translate('ComponentDescriptions', 'Index Hinge, Middle Up')),
        ('115', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit')),
        ('116', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Index Bent')),
        ('117', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Middle Bent')),
        ('118', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Cup')),
        ('119', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Hinge')),
        ('11a', qApp.instance().translate('ComponentDescriptions', 'Index Middle Cross')),
        ('11b', qApp.instance().translate('ComponentDescriptions', 'Index Middle Cross on Circle')),
        ('11c', qApp.instance().translate('ComponentDescriptions', 'Middle Bent Over Index')),
        ('11d', qApp.instance().translate('ComponentDescriptions', 'Index Bent Over Middle')),
        ('11e', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb')),
        ('11f', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb on Circle')),
        ('120', qApp.instance().translate('ComponentDescriptions', 'Index Middle Straight, Thumb Bent')),
        ('121', qApp.instance().translate('ComponentDescriptions', 'Index Middle Bent, Thumb Straight')),
        ('122', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb Bent')),
        ('123', qApp.instance().translate('ComponentDescriptions', 'Index Middle Hinge Spread, Thumb Side')),
        ('124', qApp.instance().translate('ComponentDescriptions', 'Index Up, Middle Hinge, Thumb Side')),
        ('125', qApp.instance().translate('ComponentDescriptions', 'Index Up, Middle Hinge, Thumb Unit')),
        ('126', qApp.instance().translate('ComponentDescriptions', 'Index Hinge, Middle Up, Thumb Side')),
        ('127', qApp.instance().translate('ComponentDescriptions', 'Index Middle Up Spread, Thumb Forward')),
        ('128', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb Cup')),
        ('129', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb Circle')),
        ('12a', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb Hook')),
        ('12b', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb Hinge')),
        ('12c', qApp.instance().translate('ComponentDescriptions', 'Thumb Between Index Middle Straight')),
        ('12d', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Thumb Side')),
        ('12e', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Thumb Side Unit')),
        ('12f', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Thumb Side Bent')),
        ('130', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Hook, Index Up')),
        ('131', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hook, Middle Up')),
        ('132', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit Hinge, Thumb Side')),
        ('133', qApp.instance().translate('ComponentDescriptions', 'Index Middle Cross, Thumb Side')),
        ('134', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit, Thumb Forward')),
        ('135', qApp.instance().translate('ComponentDescriptions', 'Index Middle Unit Cup, Thumb Forward')),
        ('136', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Cup, Index Up')),
        ('137', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Cup, Middle Up')),
        ('138', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Circle, Index Up')),
        ('139', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Circle, Index Hinge')),
        ('13a', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Angle Out, Middle Up')),
        ('13b', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Angle In, Middle Up')),
        ('13c', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Circle, Middle Up')),
        ('13d', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb, Unit Hinge')),
        ('13e', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb, Angle Out')),
        ('13f', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb, Angle')),
        ('140', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Angle Out, Index Up')),
        ('141', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Angle Out, Index Crossed')),
        ('142', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Angle, Index Up')),
        ('143', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hook, Middle Hinge')),
        ('144', qApp.instance().translate('ComponentDescriptions', 'Four Fingers')),
        ('145', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Bent')),
        ('146', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Hinge')),
        ('147', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Unit')),
        ('148', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Unit Split')),
        ('149', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Unit Claw')),
        ('14a', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Unit Bent')),
        ('14b', qApp.instance().translate('ComponentDescriptions', 'Four Fingers Unit Hinge')),
        ('14c', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread')),
        ('14d', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Heel')),
        ('14e', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread, Four Bent')),
        ('14f', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread, Four Bent Heel')),
        ('150', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Bent')),
        ('151', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Bent Heel')),
        ('152', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread, Thumb Forward')),
        ('153', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Cup')),
        ('154', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Cup Open')),
        ('155', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Hinge Open')),
        ('156', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Oval')),
        ('157', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Hinge')),
        ('158', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Hinge, Thumb Side')),
        ('159', qApp.instance().translate('ComponentDescriptions', 'Five Fingers Spread Hinge, No Thumb')),
        ('15a', qApp.instance().translate('ComponentDescriptions', 'Flat')),
        ('15b', qApp.instance().translate('ComponentDescriptions', 'Flat, Between Palm Facings')),
        ('15c', qApp.instance().translate('ComponentDescriptions', 'Flat Heel')),
        ('15d', qApp.instance().translate('ComponentDescriptions', 'Flat, Thumb Side')),
        ('15e', qApp.instance().translate('ComponentDescriptions', 'Flat, Thumb Side Heel')),
        ('15f', qApp.instance().translate('ComponentDescriptions', 'Flat, Thumb Bent')),
        ('160', qApp.instance().translate('ComponentDescriptions', 'Flat, Thumb Forward')),
        ('161', qApp.instance().translate('ComponentDescriptions', 'Flat Split Index, Thumb Side')),
        ('162', qApp.instance().translate('ComponentDescriptions', 'Flat Split Center')),
        ('163', qApp.instance().translate('ComponentDescriptions', 'Flat Split Center, Thumb Side')),
        ('164', qApp.instance().translate('ComponentDescriptions', 'Flat Split Center, Thumb Side Bent')),
        ('165', qApp.instance().translate('ComponentDescriptions', 'Flat Split Baby')),
        ('166', qApp.instance().translate('ComponentDescriptions', 'Claw')),
        ('167', qApp.instance().translate('ComponentDescriptions', 'Claw, Thumb Side')),
        ('168', qApp.instance().translate('ComponentDescriptions', 'Claw, No Thumb')),
        ('169', qApp.instance().translate('ComponentDescriptions', 'Claw, Thumb Forward')),
        ('16a', qApp.instance().translate('ComponentDescriptions', 'Hook Curlicue')),
        ('16b', qApp.instance().translate('ComponentDescriptions', 'Hook')),
        ('16c', qApp.instance().translate('ComponentDescriptions', 'Cup Open')),
        ('16d', qApp.instance().translate('ComponentDescriptions', 'Cup')),
        ('16e', qApp.instance().translate('ComponentDescriptions', 'Cup Open, Thumb Side')),
        ('16f', qApp.instance().translate('ComponentDescriptions', 'Cup, Thumb Side')),
        ('170', qApp.instance().translate('ComponentDescriptions', 'Cup Open, No Thumb')),
        ('171', qApp.instance().translate('ComponentDescriptions', 'Cup, No Thumb')),
        ('172', qApp.instance().translate('ComponentDescriptions', 'Cup Open, Thumb Forward')),
        ('173', qApp.instance().translate('ComponentDescriptions', 'Cup, Thumb Forward')),
        ('174', qApp.instance().translate('ComponentDescriptions', 'Curlicue Open')),
        ('175', qApp.instance().translate('ComponentDescriptions', 'Curlicue')),
        ('176', qApp.instance().translate('ComponentDescriptions', 'Circle')),
        ('177', qApp.instance().translate('ComponentDescriptions', 'Oval')),
        ('178', qApp.instance().translate('ComponentDescriptions', 'Oval, Thumb Side')),
        ('179', qApp.instance().translate('ComponentDescriptions', 'Oval, No Thumb')),
        ('17a', qApp.instance().translate('ComponentDescriptions', 'Oval, Thumb Forward')),
        ('17b', qApp.instance().translate('ComponentDescriptions', 'Hinge Open')),
        ('17c', qApp.instance().translate('ComponentDescriptions', 'Hinge Open, Thumb Forward')),
        ('17d', qApp.instance().translate('ComponentDescriptions', 'Hinge')),
        ('17e', qApp.instance().translate('ComponentDescriptions', 'Hinge Small')),
        ('17f', qApp.instance().translate('ComponentDescriptions', 'Hinge Open, Thumb Side')),
        ('180', qApp.instance().translate('ComponentDescriptions', 'Hinge, Thumb Side')),
        ('181', qApp.instance().translate('ComponentDescriptions', 'Hinge Open, No Thumb')),
        ('182', qApp.instance().translate('ComponentDescriptions', 'Hinge, No Thumb')),
        ('183', qApp.instance().translate('ComponentDescriptions', 'Hinge, Thumb Side Touches Index')),
        ('184', qApp.instance().translate('ComponentDescriptions', 'Hinge, Thumb Between Middle Ring')),
        ('185', qApp.instance().translate('ComponentDescriptions', 'Angle')),
        ('186', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring')),
        ('187', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring on Circle')),
        ('188', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring on Hinge')),
        ('189', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring on Angle')),
        ('18a', qApp.instance().translate('ComponentDescriptions', 'Baby Hinge')),
        ('18b', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring, Bent')),
        ('18c', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring, Unit')),
        ('18d', qApp.instance().translate('ComponentDescriptions', 'Index Middle Ring, Unit Hinge')),
        ('18e', qApp.instance().translate('ComponentDescriptions', 'Baby Down')),
        ('18f', qApp.instance().translate('ComponentDescriptions', 'Baby Down, Ripple Straight')),
        ('190', qApp.instance().translate('ComponentDescriptions', 'Baby Down, Ripple Curved')),
        ('191', qApp.instance().translate('ComponentDescriptions', 'Baby Down, Others Circle')),
        ('192', qApp.instance().translate('ComponentDescriptions', 'Baby Up')),
        ('193', qApp.instance().translate('ComponentDescriptions', 'Baby Up on Fist Thumb Under')),
        ('194', qApp.instance().translate('ComponentDescriptions', 'Baby Up on Circle')),
        ('195', qApp.instance().translate('ComponentDescriptions', 'Baby Up on Oval')),
        ('196', qApp.instance().translate('ComponentDescriptions', 'Baby Up on Angle')),
        ('197', qApp.instance().translate('ComponentDescriptions', 'Baby Raised Knuckle')),
        ('198', qApp.instance().translate('ComponentDescriptions', 'Baby Bent')),
        ('199', qApp.instance().translate('ComponentDescriptions', 'Baby Touches Thumb')),
        ('19a', qApp.instance().translate('ComponentDescriptions', 'Baby Thumb')),
        ('19b', qApp.instance().translate('ComponentDescriptions', 'Baby Thumb on Hinge')),
        ('19c', qApp.instance().translate('ComponentDescriptions', 'Baby Index Thumb')),
        ('19d', qApp.instance().translate('ComponentDescriptions', 'Baby Index Thumb on Hinge')),
        ('19e', qApp.instance().translate('ComponentDescriptions', 'Baby Index Thumb, Index Thumb Angle Out')),
        ('19f', qApp.instance().translate('ComponentDescriptions', 'Baby Index Thumb, Index Thumb Angle')),
        ('1a0', qApp.instance().translate('ComponentDescriptions', 'Baby Index')),
        ('1a1', qApp.instance().translate('ComponentDescriptions', 'Baby Index on Circle')),
        ('1a2', qApp.instance().translate('ComponentDescriptions', 'Baby Index on Hinge')),
        ('1a3', qApp.instance().translate('ComponentDescriptions', 'Baby Index on Angle')),
        ('1a4', qApp.instance().translate('ComponentDescriptions', 'Index Middle Baby')),
        ('1a5', qApp.instance().translate('ComponentDescriptions', 'Index Middle Baby on Circle')),
        ('1a6', qApp.instance().translate('ComponentDescriptions', 'Index Middle Baby on Hinge')),
        ('1a7', qApp.instance().translate('ComponentDescriptions', 'Ring Hinge')),
        ('1a8', qApp.instance().translate('ComponentDescriptions', 'Index Middle Baby on Angle')),
        ('1a9', qApp.instance().translate('ComponentDescriptions', 'Index Middle Cross with Baby')),
        ('1aa', qApp.instance().translate('ComponentDescriptions', 'Index Middle Cross with Baby on Circle')),
        ('1ab', qApp.instance().translate('ComponentDescriptions', 'Ring Down')),
        ('1ac', qApp.instance().translate('ComponentDescriptions', 'Ring Down, Index Thumb Hook, Middle Hinge')),
        ('1ad', qApp.instance().translate('ComponentDescriptions', 'Ring Down, Middle Thumb Angle, Index Cross')),
        ('1ae', qApp.instance().translate('ComponentDescriptions', 'Ring Up')),
        ('1af', qApp.instance().translate('ComponentDescriptions', 'Ring Raised Knuckle')),
        ('1b0', qApp.instance().translate('ComponentDescriptions', 'Ring Baby')),
        ('1b1', qApp.instance().translate('ComponentDescriptions', 'Ring Baby on Circle')),
        ('1b2', qApp.instance().translate('ComponentDescriptions', 'Ring Baby on Oval')),
        ('1b3', qApp.instance().translate('ComponentDescriptions', 'Ring Baby on Angle')),
        ('1b4', qApp.instance().translate('ComponentDescriptions', 'Ring Middle')),
        ('1b5', qApp.instance().translate('ComponentDescriptions', 'Ring Middle Unit')),
        ('1b6', qApp.instance().translate('ComponentDescriptions', 'Ring Middle Raised Knuckles')),
        ('1b7', qApp.instance().translate('ComponentDescriptions', 'Ring Index')),
        ('1b8', qApp.instance().translate('ComponentDescriptions', 'Ring Thumb')),
        ('1b9', qApp.instance().translate('ComponentDescriptions', 'Ring Thumb Hook')),
        ('1ba', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby')),
        ('1bb', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Circle')),
        ('1bc', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Curlicue')),
        ('1bd', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Hook Out')),
        ('1be', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Hook In')),
        ('1bf', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Hook Under')),
        ('1c0', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Cup')),
        ('1c1', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Hinge')),
        ('1c2', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Angle Out')),
        ('1c3', qApp.instance().translate('ComponentDescriptions', 'Index Ring Baby on Angle')),
        ('1c4', qApp.instance().translate('ComponentDescriptions', 'Middle Down')),
        ('1c5', qApp.instance().translate('ComponentDescriptions', 'Middle Hinge')),
        ('1c6', qApp.instance().translate('ComponentDescriptions', 'Middle Up')),
        ('1c7', qApp.instance().translate('ComponentDescriptions', 'Middle Up on Circle')),
        ('1c8', qApp.instance().translate('ComponentDescriptions', 'Middle Raised Knuckle')),
        ('1c9', qApp.instance().translate('ComponentDescriptions', 'Middle Up, Thumb Side')),
        ('1ca', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Hook')),
        ('1cb', qApp.instance().translate('ComponentDescriptions', 'Middle Thumb Baby')),
        ('1cc', qApp.instance().translate('ComponentDescriptions', 'Middle Baby')),
        ('1cd', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby')),
        ('1ce', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Circle')),
        ('1cf', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Curlicue')),
        ('1d0', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Cup')),
        ('1d1', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Hinge')),
        ('1d2', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Angle Out')),
        ('1d3', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Angle In')),
        ('1d4', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby on Angle')),
        ('1d5', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Bent')),
        ('1d6', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Unit on Claw')),
        ('1d7', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Unit on Claw Side')),
        ('1d8', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Unit on Hook Out')),
        ('1d9', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Unit on Hook In')),
        ('1da', qApp.instance().translate('ComponentDescriptions', 'Middle Ring Baby Unit on Hook')),
        ('1db', qApp.instance().translate('ComponentDescriptions', 'Index Hinge')),
        ('1dc', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side')),
        ('1dd', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side on Hinge')),
        ('1de', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Thumb Diagonal')),
        ('1df', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Thumb Unit')),
        ('1e0', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Thumb Bent')),
        ('1e1', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Index Bent')),
        ('1e2', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Both Bent')),
        ('1e3', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Side, Index Hinge')),
        ('1e4', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Forward, Index Straight')),
        ('1e5', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Forward, Index Bent')),
        ('1e6', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hook')),
        ('1e7', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Curlicue')),
        ('1e8', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Curve, Thumb Inside')),
        ('1e9', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Curve, Thumb Inside on Claw')),
        ('1ea', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Curve, Thumb Under')),
        ('1eb', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Circle')),
        ('1ec', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Cup')),
        ('1ed', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Cup Open')),
        ('1ee', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hinge Open')),
        ('1ef', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hinge Large')),
        ('1f0', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hinge')),
        ('1f1', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Hinge Small')),
        ('1f2', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Angle Out')),
        ('1f3', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Angle In')),
        ('1f4', qApp.instance().translate('ComponentDescriptions', 'Index Thumb Angle')),
        ('1f5', qApp.instance().translate('ComponentDescriptions', 'Thumb')),
        ('1f6', qApp.instance().translate('ComponentDescriptions', 'Thumb Heel')),
        ('1f7', qApp.instance().translate('ComponentDescriptions', 'Thumb Side Diagonal')),
        ('1f8', qApp.instance().translate('ComponentDescriptions', 'Thumb Side Unit')),
        ('1f9', qApp.instance().translate('ComponentDescriptions', 'Thumb Side Bent')),
        ('1fa', qApp.instance().translate('ComponentDescriptions', 'Thumb Forward')),
        ('1fb', qApp.instance().translate('ComponentDescriptions', 'Thumb Between Index Middle')),
        ('1fc', qApp.instance().translate('ComponentDescriptions', 'Thumb Between Middle Ring')),
        ('1fd', qApp.instance().translate('ComponentDescriptions', 'Thumb Between Ring Baby')),
        ('1fe', qApp.instance().translate('ComponentDescriptions', 'Thumb Under Two Fingers')),
        ('1ff', qApp.instance().translate('ComponentDescriptions', 'Thumb Over Two Fingers')),
        ('200', qApp.instance().translate('ComponentDescriptions', 'Thumb Under Three Fingers')),
        ('201', qApp.instance().translate('ComponentDescriptions', 'Thumb Under Four Fingers')),
        ('202', qApp.instance().translate('ComponentDescriptions', 'Thumb Over Four Raised Knuckles')),
        ('203', qApp.instance().translate('ComponentDescriptions', 'Fist')),
        ('204', qApp.instance().translate('ComponentDescriptions', 'Fist Heel')), 
        ('214', qApp.instance().translate('ComponentDescriptions', 'Surface Symbols')),
        ('215', qApp.instance().translate('ComponentDescriptions', 'Surface Between')),
        ('2ff', qApp.instance().translate('ComponentDescriptions', 'Whole head movement')),
        ('30a', qApp.instance().translate('ComponentDescriptions', 'Forehead & eyebrow movement')),
        ('314', qApp.instance().translate('ComponentDescriptions', 'Eye movement')),
        ('32a', qApp.instance().translate('ComponentDescriptions', 'Cheek movement')),
        ('331', qApp.instance().translate('ComponentDescriptions', 'Nose movement')),
        ('335', qApp.instance().translate('ComponentDescriptions', 'Mouth movement')),
        ('368', qApp.instance().translate('ComponentDescriptions', 'Chin movement')),
        ('370', qApp.instance().translate('ComponentDescriptions', 'Other non-manual movement')), 
        ('1000', qApp.instance().translate('ComponentDescriptions', 'No hands')),
        ('1001', qApp.instance().translate('ComponentDescriptions', '1-handed')),
        ('1002', qApp.instance().translate('ComponentDescriptions', '2-handed: Only strong hand moves')),
        ('1003', qApp.instance().translate('ComponentDescriptions', '2-handed: Both move')),
        ('1004', qApp.instance().translate('ComponentDescriptions', '2-handed: Both move touching as one unit')),
        ('1005', qApp.instance().translate('ComponentDescriptions', 'Fingerspelled (mostly lexicalized)')),         
        ('1010', qApp.instance().translate('ComponentDescriptions', 'Change handshape')),
        ('1011', qApp.instance().translate('ComponentDescriptions', 'Change orientation')),
        ('1012', qApp.instance().translate('ComponentDescriptions', 'Hand changes location')),         
        ('1013', qApp.instance().translate('ComponentDescriptions', 'No change (in handshape, orientation, or location)')),
        ('1021', qApp.instance().translate('ComponentDescriptions', 'Straight')),
        ('1022', qApp.instance().translate('ComponentDescriptions', 'Curved')),
        ('1023', qApp.instance().translate('ComponentDescriptions', 'Circular')),
        ('1024', qApp.instance().translate('ComponentDescriptions', 'Complex')),
        ('1025', qApp.instance().translate('ComponentDescriptions', 'Toward body')),
        ('1026', qApp.instance().translate('ComponentDescriptions', 'Away from body')),
        ('1027', qApp.instance().translate('ComponentDescriptions', 'Not consistent toward/away')),
        ('1028', qApp.instance().translate('ComponentDescriptions', 'Repetition: 1x')),
        ('1029', qApp.instance().translate('ComponentDescriptions', 'Repetition: 2+')),        
        ('102a', qApp.instance().translate('ComponentDescriptions', 'Fast (deprecated)')),
        ('102b', qApp.instance().translate('ComponentDescriptions', 'Slow (deprecated)')),
        ('102c', qApp.instance().translate('ComponentDescriptions', 'Tense (deprecated)')),
        ('102d', qApp.instance().translate('ComponentDescriptions', 'Relaxed (deprecated)')),         
        ('1030', qApp.instance().translate('ComponentDescriptions', 'Touch')),
        ('1031', qApp.instance().translate('ComponentDescriptions', 'Grasp')),
        ('1032', qApp.instance().translate('ComponentDescriptions', 'Strike (deprecated)')),
        ('1033', qApp.instance().translate('ComponentDescriptions', 'Brush (deprecated)')),
        ('1034', qApp.instance().translate('ComponentDescriptions', 'Rub (deprecated)')),
        ('1035', qApp.instance().translate('ComponentDescriptions', 'Almost touch (near)'))     
        ])
    
    def symbol_group_dict(self):
        return OrderedDict([
        ('100', qApp.instance().translate('ComponentDescriptions', 'Index')), 
        ('10e', qApp.instance().translate('ComponentDescriptions', 'Index Middle')), 
        ('11e', qApp.instance().translate('ComponentDescriptions', 'Index Middle Thumb')), 
        ('144', qApp.instance().translate('ComponentDescriptions', 'Four Fingers')), 
        ('14c', qApp.instance().translate('ComponentDescriptions', 'Five Fingers')), 
        ('186', qApp.instance().translate('ComponentDescriptions', 'Baby Finger')), 
        ('1a4', qApp.instance().translate('ComponentDescriptions', 'Ring Finger')), 
        ('1ba', qApp.instance().translate('ComponentDescriptions', 'Middle Finger')), 
        ('1cd', qApp.instance().translate('ComponentDescriptions', 'Index Thumb')), 
        ('1f5', qApp.instance().translate('ComponentDescriptions', 'Thumb')), 
        ])
    
                