name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyQt5 pyinstaller pyuca

      - name: Build the application
        run: python build_win32.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SooSL-Windows
          path: dist/
