name: Build macOS Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyQt5 pyinstaller

      - name: Build the application
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SooSL-Launcher-macOS
          path: dist/
